# Header
menu:
  Home: /
  Blog: http://blog.billryan.me
  Archives: /archives
  About: http://blog.billryan.me/about

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-32317667-4
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
