# Header
menu:
  Home: /
  Blog: /
  Archives: /archives
  About: /about

rss: http://feed.billryan.me/billryan

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
#- category
#- tagcloud
- recent_posts

# Miscellaneous
google_analytics: UA-32317667-4
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
