# Header
menu:
  About: http://www.yuanbin.me
  Blog: /
  编程笔记: http://prog-notes.yuanbin.me
  算法练习: http://algorithm.yuanbin.me
  Archives: /archives

rss: http://feed.billryan.me/billryan

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
#- category
#- tagcloud
- recent_posts

# Miscellaneous
google_analytics: UA-32317667-4
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
